Fix compilation with PostgreSQL v16
Fixes the following compilation error:

```
pending.c: In function ‘storeData’:
pending.c:456:39: error: incompatible type for argument 1 of ‘PointerGetDatum’
  456 |         planData[0] = PointerGetDatum(isKey);
      |                                       ^~~~~
      |                                       |
      |                                       _Bool
In file included from pending.c:33:
/usr/include/postgresql/server/postgres.h:322:29: note: expected ‘const void *’ but argument is of type ‘_Bool’
  322 | PointerGetDatum(const void *X)
      |                 ~~~~~~~~~~~~^
make: *** [<builtin>: pending.o] Error 1
```

Since `isKey` is a bool, I changed `PointerGetDatum` to `BoolGetDatum`.