Missing import
Fixes the following error:

pending.c:154:34: error: dereferencing pointer to incomplete type
   tupdesc = trigdata->tg_relation->rd_att;
                                  ^
pending.c: In function ‘storePending’: